### ISSUE TITLE
add out of scope answer template for editors

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/dev_guide#23]

**Comment by noamross** [comment]
Language about the different scopes of our activities should also be in the policies document

**Comment by maelle** [comment]
For reference here are good answers by @noamross :wink:

https://discuss.ropensci.org/t/dataspice-codebook-and-ropensci-scope/1179/2?u=noamross

https://github.com/ropensci/onboarding/issues/221#issuecomment-394232413
