### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by annakrystalli** [ropenscilabs/dev_guide#26]
It might be good to also develop some documentation on contributing to this guide? 

That could just live in the README or in a contributing.md. Either way, some things to cover:

- PRs for new editors with perhaps direct pushes at a later stage
- clarify the tools used to maintain the gitbook 
- outline build and commit procedure (a code walkthrough?)
- specify any dependencies (ie when I tried to `bookdown::serve_build()`, it failed because I didn't have package `airtabler` installed. This is not on cran so a link to the repo or a code snippet:  ```r devtools::install_github("bergant/airtabler")``` would be useful.
- anything else that arises?

**Comment by annakrystalli** [comment]
Re: airtable, also setting up an `AIRTABLE_API_KEY`

**Comment by maelle** [comment]
Good points!

Maybe I could use Travis to build it, will look at ropenscilabs/tic

**Comment by maelle** [comment]
https://github.com/krlmlr/tic.bookdown

**Comment by noamross** [comment]
If you want to build automatically on Travis, see https://github.com/ecohealthalliance/eha-ma-handbook . You'll pretty much just need to copy `travis.yml`, `_build.sh`, and `_deploy.sh`, add GitHub and Airtable API keys as secure variables to Travis, and switch to `gh-pages` branch docs rather than than `docs/` folder.

**Comment by noamross** [comment]
Oh, and you'll need a DESCRIPTION for package dependencies.

**Comment by maelle** [comment]
Thanks @noamross , I was hoping `tic` had a "recipe" written down, but not yet, there's only a link to an example like your repo.

**Comment by maelle** [comment]
I'm not sure I understand the current error message on Travis, will investigate https://travis-ci.org/ropenscilabs/dev_guide/builds/391096750#L2367

**Comment by maelle** [comment]
am trying the tic setup 🤞

**Comment by maelle** [comment]
Now it builds on Travis and I set the site to gh-pages but I think I got sthg wrong, now the site is the README

**Comment by maelle** [comment]
I need to add a deploy key
